apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: "https://argoproj.github.io/argo-helm"
  chart: argo-cd
  version: "5.34.3"
  targetNamespace: argocd
  valuesContent: |-
    configs:
      params:
        server.insecure: true
      credentialTemplates:
        ssh-creds:
          url: git@github.com:input-output-hk
          sshPrivateKey: |
            #ENTER PRIVATE KEY HERE
    server:
      config:
        resource.customizations: |
          argoproj.io/Application:
            health.lua: |
              hs = {}
              hs.status = "Progressing"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.health ~= nil then
                  hs.status = obj.status.health.status
                  if obj.status.health.message ~= nil then
                    hs.message = obj.status.health.message
                  end
                end
              end
              return hs
