apiVersion: v1
kind: Namespace
metadata:
  name: gitea

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system
spec:
  repo: https://dl.gitea.io/charts/
  chart: gitea
  targetNamespace: gitea
  valuesContent: |-
    gitea:
      admin:
        username: "local-prism"
        password: "atala"
        email: "git@atalaprism.io"
