apiVersion: v1
data:
  project: ZGVmYXVsdA==
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206aW5wdXQtb3V0cHV0LWhrL2F0YWxhLXByaXNtLWhlbG0tY2hhcnRzLmdpdA==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: helm-chart-repo
  namespace: argocd
type: Opaque
