apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "atala-prism-dev-deployments-github-docker-registry-key"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson | b64dec }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.dockerRegistryToken }}

---
# Requires wallet to be created (atm it's done through terraform module)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.global.cardanoNode }}-{{ .Values.global.cardanoWallet }}"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: {{ .Values.global.cardanoWallet }}

---
{{- $root := . -}}
{{- range $consumer := .Values.consumers }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ $root.Values.keyPrefix }}-{{ $consumer | lower }}"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ $root.Values.secretStore | quote }}
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "{{ $root.Values.keyPrefix }}-{{ $consumer | lower }}"
---
{{- end }}
