apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: prism-agent-server
spec:
  selector:
    app.kubernetes.io/name: prism-agent-server
  ports:
    - protocol: "TCP"
      port: 8085
      targetPort: 8085
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: prism-agent-server-didcomm
spec:
  selector:
    app.kubernetes.io/name: prism-agent-server
  ports:
    - protocol: "TCP"
      port: 8090
      targetPort: 8090
  type: ClusterIP
