components:
  parameters:
    offset:
      name: offset
      description: |
        Pagination offset starting from 0.
        If the parameter is not specifed, it defaults to 0.
      in: query
      required: false
      schema:
        type: integer
        format: int32
    limit:
      name: limit
      description:
        Pagination limit. The maximum number of items in the paginated response.
        If the parameter is not specified, it defualt to 100.
      in: query
      required: false
      schema:
        type: integer
        format: int32
